services:
  web:
    image: nginx:latest
    container_name: mi_servidor_web
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs

  sftp:
    image: atmoz/sftp
    container_name: mi_servidor_sftp
    ports:
      - "2222:22"
    environment:
      - SFTP_USERS=alumno:pass1234:::upload
    volumes:
      - ./html:/home/alumno/upload
